"""
OAuth 2.0 / OIDC models — SIA backend acts as the identity provider for all agents.

OAuthClient  — a registered agent application (HR Agent, MARK Agent, future agents).
OAuthAuthorizationCode — short-lived single-use codes exchanged for tokens.
"""

import uuid
import secrets
from django.db import models
from django.contrib.auth.hashers import make_password, check_password
from django.utils.crypto import get_random_string
from django.utils import timezone


class OAuthClient(models.Model):
    """
    A registered OAuth 2.0 client (agent application).
    client_secret is stored hashed; the full secret is returned once on creation.
    """

    AGENT_TYPE_CHOICES = [
        ("mark", "Mark's Agent"),
        ("hr", "HR Agent"),
    ]

    client_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Hashed secret storage (same pattern as TenantAPIKey)
    client_secret_hash = models.CharField(max_length=255)
    client_secret_prefix = models.CharField(
        max_length=10, help_text="First 10 chars — for display/identification only"
    )

    name = models.CharField(max_length=100, help_text="E.g. 'HR Agent Production'")
    agent_type = models.CharField(max_length=10, choices=AGENT_TYPE_CHOICES)
    redirect_uris = models.JSONField(
        default=list, help_text="List of allowed redirect URIs"
    )

    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "oauth_clients"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["agent_type"]),
            models.Index(fields=["client_secret_prefix"]),
        ]

    def __str__(self):
        return f"{self.name} ({self.agent_type})"

    @classmethod
    def generate_secret(cls):
        """Return (full_secret, secret_hash, secret_prefix). full_secret shown once only."""
        full_secret = f"sia_oauth_{get_random_string(32)}_{secrets.token_urlsafe(16)}"
        return full_secret, make_password(full_secret), full_secret[:10]

    def verify_secret(self, secret: str) -> bool:
        return check_password(secret, self.client_secret_hash)

    def is_redirect_uri_allowed(self, uri: str) -> bool:
        return uri in self.redirect_uris


class OAuthAuthorizationCode(models.Model):
    """
    Short-lived (10 min), single-use authorization codes.
    Generated by POST /oauth/authorize/, consumed by POST /oauth/token/.
    """

    code = models.CharField(max_length=80, unique=True, db_index=True)
    client = models.ForeignKey(
        OAuthClient, on_delete=models.CASCADE, related_name="auth_codes"
    )
    user = models.ForeignKey(
        "auth_app.UserProfile",
        on_delete=models.CASCADE,
        related_name="oauth_codes",
    )
    redirect_uri = models.CharField(max_length=500)
    scopes = models.CharField(max_length=100, default="openid profile")
    expires_at = models.DateTimeField()
    is_used = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "oauth_authorization_codes"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["client", "-created_at"]),
            models.Index(fields=["is_used", "expires_at"]),
        ]

    def __str__(self):
        status = "used" if self.is_used else "active"
        return f"{self.client.name} — {self.user.email} — {status}"

    def is_valid(self) -> bool:
        return not self.is_used and timezone.now() < self.expires_at

    @classmethod
    def generate_code(cls) -> str:
        return get_random_string(80)
