# Generated by Django 6.0.2 on 2026-02-13 09:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique session identifier', primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, help_text="User's name", max_length=255, null=True)),
                ('user_email', models.EmailField(blank=True, help_text="User's email for follow-up", max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('user_phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, help_text="User's company name", max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('qualified', 'Qualified Lead'), ('archived', 'Archived'), ('escalated', 'Escalated to Human')], default='active', help_text='Current session status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Session start time')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last message time')),
                ('is_qualified_lead', models.BooleanField(default=False, help_text='Whether user is qualified for demo')),
                ('interested_in', models.JSONField(blank=True, default=list, help_text='Products/features user is interested in (ARGO, MARK, CONSUELO)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True)),
                ('user_agent', models.TextField(blank=True, help_text="User's browser info", null=True)),
                ('total_messages', models.IntegerField(default=0, help_text='Total messages in this session')),
                ('conversation_duration', models.DurationField(blank=True, help_text='Total time spent in conversation', null=True)),
            ],
            options={
                'db_table': 'chat_sessions',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['-last_activity'], name='chat_sessio_last_ac_f673b9_idx'), models.Index(fields=['user_email'], name='chat_sessio_user_em_91e969_idx'), models.Index(fields=['status'], name='chat_sessio_status_f6889c_idx')],
            },
        ),
        migrations.CreateModel(
            name='BotPerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_response_time_ms', models.FloatField(help_text='Average response time in milliseconds', null=True)),
                ('user_satisfaction_score', models.IntegerField(blank=True, help_text='User satisfaction rating (1-5)', null=True)),
                ('escalation_required', models.BooleanField(default=False, help_text='Whether conversation needed human escalation')),
                ('converted_to_lead', models.BooleanField(default=False, help_text='Whether user became a qualified lead')),
                ('demo_booked', models.BooleanField(default=False, help_text='Whether user booked a demo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'bot_performance_metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(default='greeting', help_text='Current conversation step (greeting, info_collection, product_discussion, etc.)', max_length=50)),
                ('has_name', models.BooleanField(default=False)),
                ('has_email', models.BooleanField(default=False)),
                ('has_company', models.BooleanField(default=False)),
                ('preferred_products', models.JSONField(blank=True, default=list, help_text='List of products user showed interest in')),
                ('pain_points', models.JSONField(blank=True, default=list, help_text="User's mentioned pain points or challenges")),
                ('questions_asked', models.JSONField(blank=True, default=list, help_text='Topics/questions user has asked about')),
                ('asked_for_demo', models.BooleanField(default=False, help_text='User requested a demo')),
                ('asked_for_pricing', models.BooleanField(default=False, help_text='User asked about pricing')),
                ('needs_human_handoff', models.BooleanField(default=False, help_text='Conversation needs human intervention')),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Additional custom context data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(help_text='Associated chat session', on_delete=django.db.models.deletion.CASCADE, related_name='context', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'conversation_contexts',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('bot', 'Bot Response'), ('system', 'System Message')], default='user', help_text='Type of message', max_length=10)),
                ('content', models.TextField(help_text='Message content')),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Time taken to generate response (milliseconds)', null=True)),
                ('model_used', models.CharField(blank=True, default='gemini-2.5-flash', help_text='AI model used for response', max_length=100, null=True)),
                ('detected_intent', models.CharField(blank=True, help_text='Detected user intent (product_inquiry, pricing, demo_request, etc.)', max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='Confidence score for intent detection (0-1)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Message timestamp')),
                ('parent_message', models.ForeignKey(blank=True, help_text='Parent message (for threading)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chatbot.chatmessage')),
                ('session', models.ForeignKey(help_text='Associated chat session', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['session', 'timestamp'], name='chat_messag_session_4a3fea_idx'), models.Index(fields=['message_type'], name='chat_messag_message_b8fb34_idx'), models.Index(fields=['detected_intent'], name='chat_messag_detecte_f9305b_idx')],
            },
        ),
    ]
