# Generated by Django 5.0.1 on 2026-02-18 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agentrequestlog',
            new_name='agent_reque_tenant__22547d_idx',
            old_name='agentrequ_tenant__88bb00_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrequestlog',
            new_name='agent_reque_agent_t_759dca_idx',
            old_name='agentrequ_agent_t_9b381c_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrequestlog',
            new_name='agent_reque_status_7b1b9a_idx',
            old_name='agentrequ_status_26e84f_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrequestlog',
            new_name='agent_reque_request_d4859e_idx',
            old_name='agentrequ_request_3c7c71_idx',
        ),
        migrations.RenameIndex(
            model_name='agentrequestlog',
            new_name='agent_reque_created_0ede9d_idx',
            old_name='agentrequ_created_53f5d7_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_slug_3181c2_idx',
            old_name='tenants_slug_5a0f92_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_status_80d9b6_idx',
            old_name='tenants_status_8a5f1c_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_subscri_aa3140_idx',
            old_name='tenants_subscri_7c5e3a_idx',
        ),
        migrations.RenameIndex(
            model_name='tenant',
            new_name='tenants_email_64287b_idx',
            old_name='tenants_email_6c6a0c_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantapikey',
            new_name='tenant_api__key_pre_65c034_idx',
            old_name='tenantapike_key_pr_8ed5b5_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantapikey',
            new_name='tenant_api__is_acti_e45f98_idx',
            old_name='tenantapike_is_acti_b55bda_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantapikey',
            new_name='tenant_api__tenant__14c4b8_idx',
            old_name='tenantapike_tenant__d10a39_idx',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(help_text='Primary contact email for the tenant', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='tenantuser',
            name='email',
            field=models.EmailField(help_text="User's email address", max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
