# Generated by Django 5.0.1 on 2026-02-27 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_secret_hash', models.CharField(max_length=255)),
                ('client_secret_prefix', models.CharField(help_text='First 10 chars — for display/identification only', max_length=10)),
                ('name', models.CharField(help_text="E.g. 'HR Agent Production'", max_length=100)),
                ('agent_type', models.CharField(choices=[('mark', "Mark's Agent"), ('hr', 'HR Agent')], max_length=10)),
                ('redirect_uris', models.JSONField(default=list, help_text='List of allowed redirect URIs')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'oauth_clients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent_type'], name='oauth_clien_agent_t_f91288_idx'), models.Index(fields=['client_secret_prefix'], name='oauth_clien_client__64459f_idx')],
            },
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=80, unique=True)),
                ('redirect_uri', models.CharField(max_length=500)),
                ('scopes', models.CharField(default='openid profile', max_length=100)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_codes', to='auth_app.userprofile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='oauth.oauthclient')),
            ],
            options={
                'db_table': 'oauth_authorization_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', '-created_at'], name='oauth_autho_client__5c1929_idx'), models.Index(fields=['is_used', 'expires_at'], name='oauth_autho_is_used_d8ef4f_idx')],
            },
        ),
    ]
